---
- name: cloud-1 project
  hosts: all
  become: yes

  tasks:
    - name: setup docker
      include: ./playbooks/setup_docker.yaml

    - name: setup envirment
      include: ./playbooks/setup_envirment.yaml

    - name: update env in inception
      include: ./playbooks/update_env.yml

    - name: Build inception project
      command: make
      args:
        chdir: /home/{{ owner }}/inception
