---
- name: Get OS information
  command: uname -a
  register: os_info
  changed_when: false

- name: Install Docker for Ubuntu/Debian
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Docker for RedHat-based systems
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Docker for other systems (fallback)
  debug:
    msg: "Fallback installation for Docker (Unrecognized OS)"
  when: ansible_facts['os_family'] not in ['Debian', 'RedHat']
