---
- name: Check if .env file exists
  stat:
    path: "/home/{{ owner }}/inception/srcs/.env"
  register: env_file_check

- name: Create default .env file if it doesn't exist
  copy:
    dest: "/home/{{ owner }}/inception/srcs/.env"
    content: |
      # general
      USERNAME=
      DOMAIN_NAME=

      # certificate
      CERTS_=
      KEYOUT_=

      # MYSQL SETUP
      MYSQL_DB=
      MYSQL_USER=
      MYSQL_PASSWORD=
      MYSQL_ROOT_PASSWORD=
      MYSQL_HOSTNAME=

      # REDIS SETUP

      # WORDPRESS SETUP
      WP_TITLE=
      WP_ROOT_USER_USERNAME=
      WP_ROOT_USER_EMAIL=
      WP_ROOT_USER_ROLE=
      WP_ROOT_USER_PASSWORD=

      WP_USER_USERNAME=
      WP_USER_EMAIL=
      WP_USER_ROLE=
      WP_USER_PASSWORD=
  when: not env_file_check.stat.exists
  notify: Warn about filling the .env file

- name: Update USERNAME and DOMAIN_NAME in .env
  lineinfile:
    path: "/home/{{ owner }}/inception/srcs/.env"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regex: '^USERNAME=.*$', line: "USERNAME={{ owner }}" }
    - { regex: '^DOMAIN_NAME=.*$', line: "DOMAIN_NAME={{ owner }}.42.fr" }
  when: env_file_check.stat.exists

- name: Warn about filling the .env file
  debug:
    msg: |
      The .env file has been created with minimal values (USERNAME and DOMAIN_NAME).
      Please fill in the remaining parameters manually:
      - CERTS_
      - KEYOUT_
      - MYSQL_DB
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_HOSTNAME
      - WP_TITLE
      and other settings.
  when: not env_file_check.stat.exists

